---
# Source: workshop-gitops-apps-deploy/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day-2-sno-1
  namespace: openshift-operators
spec:
  destination:
    server: https://kubernetes.default.svc
  project: dev
  source:
    helm:
      parameters:
        - name: global.oauth.enabled
          value: 'false'
        - name: global.operators.enabled
          value: 'false'
        - name: global.nmstate.enabled
          value: 'false'
        - name: global.monitoring.enabled
          value: 'false'     
        - name: global.namespace.enabled
          value: 'false'                         
        - name: global.bookinfo.enabled
          value: 'false'     
        - name: operators.nmstate.enabled
          value: 'false'              
      valueFiles:
        - charts/operators/values.yaml
        - charts/oauth/values.yaml
        - charts/bookinfo/values.yaml
        - charts/monitoring/values.yaml   
        - charts/nmstate/values.yaml  
        - charts/namespace/values.yaml  
    path: .
    repoURL: https://github.com/romerobu/helm-infra-gitops-workshop.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
