{{- range $key, $val := $.Values.clusters }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: day-2-{{ $key }}
  namespace: {{ $val.application_namespace }}
spec:
  destination:
    server: {{ $val.destination }}
    namespace: ''
  project: {{ $val.project }}
  source:
    helm:
      parameters:
        - name: global.oauth.enabled
          value: 'false'
        - name: global.operators.enabled
          value: 'false'
        - name: global.nmstate.enabled
          value: 'false'
        - name: global.monitoring.enabled
          value: 'false'     
        - name: global.namespace.enabled
          value: 'false'                         
        - name: global.bookinfo.enabled
          value: 'false'     
        - name: operators.nmstate.enabled
          value: 'false'              
      valueFiles:
        - charts/operators/values.yaml
        - charts/oauth/values.yaml
        - charts/bookinfo/values.yaml
        - charts/monitoring/values.yaml   
        - charts/nmstate/values.yaml  
        - charts/namespace/values.yaml  
    path: {{ $val.code.path }}
    repoURL: {{ $val.code.repo }}
    targetRevision: {{ $val.code.target }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}      